"""added patients table

Revision ID: 457836001e94
Revises: 1936c480bea5
Create Date: 2024-01-08 23:29:46.269854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '457836001e94'
down_revision: Union[str, None] = '1936c480bea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('Phone_number', sa.String(), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('addmission_date', sa.Date(), nullable=True),
    sa.Column('medication', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    # ### end Alembic commands ###
