"""added many to many relationship

Revision ID: 5c0b648fe075
Revises: 616eef8ba70e
Create Date: 2024-01-10 22:24:44.350835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0b648fe075'
down_revision: Union[str, None] = '616eef8ba70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('patients', 'Phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('Phone_number', sa.VARCHAR(), nullable=True))
    op.drop_column('patients', 'phone_number')
    # ### end Alembic commands ###
